### PR TITLE
[WIP] Update KCC from upstream SDCC in order to bring more features

### PR DESCRIPTION
**Pull request by aviallon**
Updated the whole KCC codebase to the latest SDCC patches. It does help to fix a few bugs here and there, but sadly there isn't proper struct support yet. And that is very sad.

### CODE REVIEW

**Comment by pixelherodev** [comment]
This... is going to take a while to review.

The biggest thing that leaps out at me is that formatting has changed, a lot. Was that deliberate?

**Comment by aviallon** [comment]
@pixelherodev not entirely. At first, I wanted to cleanly import changes from SDCC. But the delta was just way too enormous. So reimplementing every KCC patch from scratch seemed easier.

**Comment by pixelherodev** [comment]
Yeah... we really need to work out a process for this for the future.

**Comment by MaxLeiter** [comment]
@aviallon if you can find a way to accomplish this while keeping our current formatting we'll be a lot faster at reviewing. This diff is kind of a nightmare atm

**Comment by aviallon** [comment]
I will try of course.
I expect it to be ready in a month.

**Comment by aviallon** [comment]
> Yeah... we really need to work out a process for this for the future.
> 

Patch files?

**Pull request closed without merging**
